"""Update models for premium features and insights

Revision ID: 06b9a3f4c3cb
Revises: ddcde795ce38
Create Date: 2026-06-10 16:52:17.759161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b9a3f4c3cb'
down_revision = 'ddcde795ce38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals_snapshot', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('habits_snapshot_json', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('insight_reports', schema=None) as batch_op:
        batch_op.drop_column('habits_snapshot_json')
        batch_op.drop_column('goals_snapshot')

    # ### end Alembic commands ###
