"""added location

Revision ID: 8a82467a070c
Revises: bd2d70fd9ce1
Create Date: 2026-06-14 22:59:15.608284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a82467a070c'
down_revision = 'bd2d70fd9ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('premium_insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_label', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('premium_insights', schema=None) as batch_op:
        batch_op.drop_column('location_label')
        batch_op.drop_column('location_longitude')
        batch_op.drop_column('location_latitude')

    # ### end Alembic commands ###
