"""removed notes fromcheckin, not needed

Revision ID: bd2d70fd9ce1
Revises: cf3f681ea344
Create Date: 2026-06-13 16:06:55.615064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2d70fd9ce1'
down_revision = 'cf3f681ea344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
