"""add ai_consent and theme_preference columns

Revision ID: 99bbfa9f19c9
Revises: 545bcb12dcc4
Create Date: 2026-06-02 21:10:54.066213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bbfa9f19c9'
down_revision = '545bcb12dcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_insight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('average_mood', sa.Float(), nullable=False),
    sa.Column('top_habits', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_consent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('selected_habits', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('selected_habits')
        batch_op.drop_column('theme_preference')
        batch_op.drop_column('ai_consent')

    op.drop_table('weekly_insight')
    # ### end Alembic commands ###
